### ISSUE TITLE
README.md broken link

### ISSUE THREAD

**Issue by luzpaz** [Calinou/godot-qa-api-generator#1]
![image](https://user-images.githubusercontent.com/4140247/106262987-ca102380-61f1-11eb-8881-49d5281208bd.png)  
The link in the above screenshot is broken.

**Comment by Calinou** [comment]
I designed the README to be ready in advance once https://github.com/godotengine/godot-docs/pull/4419 is merged :slightly_smiling_face: 

Fixed by https://github.com/Calinou/godot-qa-api-generator/commit/6082596a05f05161e765507a1a19146c38d2e4cf. I'll revert that commit once the PR is merged.
